apiVersion: v1
kind: Secret
metadata:
  name: frontend-service-secret
type: Opaque
data:
  REACT_APP_USER_SERVICE_URL: aHR0cDovL2xvY2FsaG9zdDozMDAx
  REACT_APP_PRODUCT_SERVICE_URL: aHR0cDovL2xvY2FsaG9zdDozMDAy
  REACT_APP_CART_SERVICE_URL: aHR0cDovL2xvY2FsaG9zdDozMDAz
  REACT_APP_ORDER_SERVICE_URL: aHR0cDovL2xvY2FsaG9zdDozMDA0
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      containers:
        - name: frontend-service
          image: deepsjain271/frontend
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: REACT_APP_USER_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: frontend-service-secret
                  key: REACT_APP_USER_SERVICE_URL
            - name: REACT_APP_PRODUCT_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: frontend-service-secret
                  key: REACT_APP_PRODUCT_SERVICE_URL
            - name: REACT_APP_CART_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: frontend-service-secret
                  key: REACT_APP_CART_SERVICE_URL
            - name: REACT_APP_ORDER_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: frontend-service-secret
                  key: REACT_APP_ORDER_SERVICE_URL
            

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend-service
  ports:
    - port: 3000
      targetPort: 3000